spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insightHub_db
    username: postgres
    password: root123
  application:
    name: final-project
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
my_token:
  key: hereIsMySecretKeyForFinalProject
  expire_time: 86400000